export const config = {
  title: 'You (“Client”) and Gainy, Inc., a Delaware limited liability company and a Securities Exchange Commission (the “SEC”) registered investment adviser (“Gainy”), agree to enter into an investment advisory relationship (the “Agreement”) pursuant to which Gainy shall exclusively manage the assets in account(s) that you establish at DriveWealth LLC (“DriveWealth”). This Agreement is solely available to residents of the United States and its territories. This Agreement is effective as of the first day a brokerage account is opened in connection with this Agreement and is ready to receive trading instructions from Gainy (the “Effective Date”). In consideration of the mutual covenants herein, Client and Gainy agree as follows:',
  buttonText: 'I accept',
  list: [
    {
      title: '1. Services',
      content: 'Client appoints Gainy to exclusively manage one or more accounts established and owned by Client at DriveWealth (each the “<b>Client Account</b> ,” “ <b>DriveWealth Account</b> ” or “ <b>Account</b>”). Gainy shall manage the Accounts in accordance with (i) an investment plan recommended by Gainy to Client from time to time based on profile information provided by Client (“<b>Investment Profile</b> ”), and in accordance with certain additional investment options designated by Client (the “<b>Plan</b>” ), or (ii) an Investment Profile customized by Client (“<b>Client-Defined Portfolios</b>”).  Gainy shall manage such Client- Defined Portfolios in accordance with the investment allocation elected by Client, although Gainy retains full investment discretion over such Client-Defined Portfolios and its allocation. Client authorizes Gainy, on Client’s behalf and at Client’s risk, to supervise and direct the investment and reinvestment of assets in the Client Accounts, with full authority and discretion, without consultation with Client, to purchase and sell securities, including but not limited to stocks, exchange traded funds (“<b>ETFs</b>”), mutual funds (including without limitation money market mutual funds as separate investments from the Plan), and/or similarly traded instruments (collectively, the “<b>Securities</b>>”), as well as to manage cash balances within the Client Accounts. Gainy shall have the sole authority to issue trading instructions to purchase and sell Securities in the Client Accounts based on the discretionary authority granted to Gainy by Client under this Agreement. Gainy shall not have any duty or obligation to advise or take any action on behalf of Client in any legal proceedings, including bankruptcies or class actions, involving Securities held in, or formerly held in, the Account, or involving the issuers of such Securities.',
      subcontent: 'Notwithstanding anything in this Agreement to the contrary, Gainy shall have no authority hereunder to take or have possession of any assets in the Accounts or to direct delivery of any Securities or payment of any funds held in the Account to itself or to direct any disposition of such Securities or funds, except to Client, as directed by Client and to a Client controlled account, pursuant to valid legal authority, as provided in Section 8 hereof.'
    },
    {
      title: '2. Representations and Warranties.',
      content: '(a) Client represents and warrants to Gainy as follows:',
      lists: [
        'Client has the requisite legal capacity, authority, and power to execute, deliver and perform his or her obligations under this Agreement. This Agreement has been duly authorized, executed and delivered by Client and is the legal, valid, and binding agreement of Client, enforceable against Client in accordance with its terms. Client’s execution of this Agreement and the performance of his or her obligations hereunder do not conflict with or violate any obligations by which Client is bound, whether arising by contract, operation of law or otherwise. If the Client is an entity, the individual trustee, agent, representative or nominee (the “<b>Client Representative</b>”) executing this Agreement on behalf of Client has the requisite legal capacity, authority, and power to execute, deliver and perform such execution and the obligations under this Agreement as applicable. The services described herein are authorized under the Client’s applicable articles, certificate, charter, operating agreement, partnership agreement, plan document, trust or organizational, delegation or formation documents or law. Upon Gainy’s  request, Client will deliver to Gainy evidence of Client’s and Client Representative’s authority. Client will promptly notify Gainy of any change in such authority.',
        'Client is the owner or co-owner of all cash and Securities in the Account, and there are no restrictions on the pledge, hypothecation, transfer, sale or public distribution of such cash or Securities.',
        'Client acknowledges and agrees that a Plan may include portfolios of stocks or other Securities (“<b>Topic Trading Fractionals</b> ” or “<b>TTF</b>”), with each security in such portfolios playing a necessary role in the overall investment strategy and, therefore, Client understands and acknowledges that the Client cannot force exclusions or restrictions of Securities recommended by Gainy as part of the Plan or restrict or change the composition of a TTF.',
        'Client acknowledges and agrees that Gainy retains full discretion over Client-Defined Portfolios and that Client-Defined Portfolio allocations are suggestions and not directed trades.',
        'Client will provide Gainy with complete, current, and accurate information about Client’s identity, background, net worth, investing timeframe, other risk considerations, any Securities from which Client may be or become legally restricted from buying or selling and other investment accounts in the Investment Profile and will promptly update that information as Client’s circumstances change.',
        'Client acknowledges and agrees that Client must have access to a mobile phone capable of receiving SMS text messages and using a compatible operating system.',
        'Client acknowledges and agrees that Gainy or DriveWealth, as applicable, may require further documentation verifying Client’s identity or the identity of the Client’s beneficial owners, if any, and the source of funds used to make payment or deposit to Gainy. Client hereby agrees to provide such documentation as may be requested by Gainy. Furthermore, Client acknowledges and agrees that Gainy and DriveWealth, as applicable, may release confidential information regarding Client and, if applicable, any of Client’s beneficial owners, to government authorities, if Gainy, in its sole discretion, determines after consultation with counsel that releasing such information is in the best interest of Gainy.',
        'Client acknowledges and agrees that Gainy can only take instructions from Client and cannot accept instructions provided to Gainy by any third-party pursuant to a power- of-attorney document or any other document.',
        ' Client agrees to use Gainy solely for Client’s personal, non-commercial use, and not in connection with any competitive analysis (as determined by Gainy).',
        'Client acknowledges and agrees that (A) Gainy does not guarantee the performance of the Account and is not responsible to Client for any investment losses, (B) the Account is not insured against loss of income and/or principal; (C) there are significant risks associated with investing in Securities, including, but not limited to, the risk that the Account could suffer substantial diminution in value, and this risk applies even when the Account is managed by a registered investment adviser; (D) the past performance of any stock, benchmark, market index, ETF, investment portfolio or other Security does not indicate its future performance, and future transactions will be made in different Securities and different economic environments; (E) Gainy will cause the Account to invest in Securities substantially in the proportions set forth by the Plan (subject to the profile information received from Client and to various other factors, including without limitation Client deposits or withdrawals, variations in the allocations due to movements in the prices of Securities over time, revisions of the Plan by Gainy from time-to-time consistent with Client’s profile information, and Client’s elections); (F) Gainy will provide only the specific reviews and restrictions described in this Agreement and will not otherwise review or control such Account; and (G) there are significant risks associated with any investment program.',
        'Client acknowledges and agrees that Gainy’s  sole obligation hereunder is to manage the Account in accordance with the Plan, and notwithstanding any duty or obligation Client Representative may have to an entity Client, Client has not engaged Gainy to provide any individual financial planning services.',
        'Client understands and agrees that the Account will be managed solely by Gainy based on the information Client has provided to Gainy. Client further understands that if any of the information Client provides to Gainy is or becomes incomplete or inaccurate, the Account’s activities may not achieve Client’s desired investment or tax strategy, the Account may purchase Securities from which Client is restricted from purchasing at that time or the Plan may otherwise be inappropriate for Client. An Account’s transactions may be executed at approximately the same time as transactions in other client accounts managed by Gainy in accordance with other clients’ investment plan, and if the transactions are large in relation to the trading volume on that particular day, the price may be different than it would be for the execution of a smaller transaction. Client acknowledges and agrees that Gainy has sole discretion regarding the manner in which transaction orders are placed for the purchase and sale of Securities for the Client Account(s). Client further acknowledges and agrees that prices of Securities purchased and sold for the Client Account(s) may be less favorable than the prices obtained for the same Securities in similar transactions by other client accounts managed by Gainy and/or other non-related market participants.',
        'Client acknowledges and agrees that an Account’s composition and performance may be different for a variety of reasons from those of any Plan recommendation to a Client. These differences can arise each time the Plan is adjusted or rebalanced, including, but not limited to, the following instances: (A) when the Account is established and the initial Securities positions are established; (B) when Client contributes additional capital to such Account; (C) when Client revises the Investment Profile, makes any elections or changes to their allocations, or takes any other action that causes Gainy to recommend a new Plan or revise the existing Plan; (D) each time the Advisory Fee (as defined in Section 5) is charged and paid from such Account; and (E) any time Gainy adjusts its algorithm by which the composition of the Account is maintained as specified for the Plan. On any such adjustment, Gainy may adjust the Plan in its discretion to approximate the composition specified in the Plan as closely as reasonably practicable based on the conditions at the time.',
        'Client acknowledges and agrees that the Account must maintain at all times a minimum balance as set forth on the Gainy Site or App, unless the balance drops below the specified minimum due solely to decreases in the values of the Account’s Securities and not due to any withdrawals of funds while the balance of the Account met the minimum as provided in this Section 2(xvi). Without in any way limiting Gainy’s rights pursuant to Section 14 hereof, if the Account balance falls below the specified minimum, Gainy upon prior notification to the Client may liquidate the Account holdings, deliver the proceeds of the liquidation to Client, and close the Account.',
      ]
    },
    {
      title: '3. Custody',
      content: 'Client has appointed DriveWealth as its broker and custodian pursuant to a separate “Customer Brokerage and Custody Agreement.” Gainy shall not be liable to Client for any act, conduct or omission by the DriveWealth and/or the clearing broker in its capacity as broker or custodian. At no time will Gainy accept, maintain possession, or have custodial responsibility for Client’s assets or securities.'
    },
    {
      title: '4. Confidentiality',
      content: 'Except as required by law or requested by regulatory authorities, (a) Gainy agrees to maintain in confidence, consistent with Gainy’s confidentiality policies, all of Client’s non-public personal and financial information that Client furnishes to Gainy, except for information that Client explicitly agrees to share publicly, and (b) Client agrees to maintain in strict confidence all investment advice and other non-public information that Client acquires from Gainy in connection with the Account. Client agrees that Client shall not use investment recommendations and other confidential information Client receives from Gainy for any purpose other than managing the Account, including, but not limited to, developing a service that competes with the Site or Gainy’s services. Client acknowledges receipt of and consents to Gainy’s Privacy Policy available at <a href="www.gainy.app/privacy-policy" target="_blank">www.gainy.app/privacy-policy</a> . Client understands, acknowledges, and agrees that Client can opt-out certain portions of the Gainy Privacy Policy at any time; however, if the Client does opt out, Gainy may choose to terminate this Agreement and related Account(s). Notwithstanding any provisions in this Agreement to the contrary, Gainy may share Client’s non-public personal and financial information with affiliates of Gainy in connection with providing and/or enhancing the services provided to Client.'
    },
    {
      title: '5. Advisory and Platform Fees',
      lists: [
        'Gainy specifies the annual fee rate it charges a Client (the “<b>Advisory Fee</b> ”) and posts the Advisory Fee on the Client’s Account page on the Site and the App. Fees due shall be calculated by multiplying the Advisory Fee by the net market value of the Account as of the close of trading on the New York Stock Exchange (“<b>NYSE</b>”) (herein, “<b>close of markets</b>”) on such day, or as of the close of markets on the immediately preceding trading day for any day when the NYSE is closed, and then by dividing by 365 (except in any leap year, during which year the amount shall be divided by 366). Notwithstanding the foregoing, for Accounts with a total value less than $10,000 Gainy will charge a fixed annual rate (the “<b>Platform Fee</b>”) in place of the Advisory Fee. Gainy shall post the Platform Fee on the Client’s Account page on the Site and the App. For each day when the net market value of the Account as of the close of the market is less than $10,000 Gainy calculates the daily fee by dividing the annual Platform Fee by 365 except in any leap year, during which year the amount shall be divided by 366).',
        'Except as provided below, the fees due for each calendar month (consisting of the aggregate of the daily fee for each day in that calendar month) shall be due and payable in arrears no later than the tenth business day of the immediately following calendar month. Gainy will promptly notify Client of any increase or decrease in the Advisory Fee or the Platform Fee. An increase in the Advisory Fee or the Platform Fee will be effective for the Account starting in the next month that begins at least 30 days after Gainy sends or posts such notice. A reduction in the Advisory Fee or the Platform Fee will be effective for the Account starting in the next month following its reduction.',
        'If Client closes the Account, withdraws the entire balance of the Account, or otherwise terminates this Agreement on any date other than the last business day of the month (except under the circumstances covered by Section 5(b)), Client shall pay any outstanding aggregate daily fees for the period from the day immediately following the last day of the last calendar month for which Client has paid, through the effective date of such withdrawal or termination. ',
        ' If, for any reason, Gainy closes and liquidates all the positions held in the Account, Client will receive the proceeds of the liquidated portion of the Account net of any Advisory Fee or Platform Fee due, and this Agreement shall terminate.',
        'If, for any reason, there is insufficient cash available in the Account to cover the Advisory Fees or Platform Fees at the time they are charged, Gainy, in its sole discretion, may cause certain Securities in the Account to be liquidated to allow the Advisory Fee and/or Platform Fee to be deducted from the Account.',
        'Gainy reserves the right, in its sole and absolute discretion, to reduce or waive the Advisory Fee or Platform Fee for certain Client Accounts for any period of time determined by Gainy. In addition, Client agrees that Gainy may waive its fees for the Accounts of clients other than Client, without notice to Client and without waiving its fees for Client. In exercise of its sole and absolute discretion Gainy may amend or terminate any reduction or waiver of the Advisory Fee or the Platform Fee. Gainy will promptly notify Client of any increase or decrease in the reduction or waiver of the Advisory Fee or the Platform Fee. A change in the waiver or reduction of the Advisory Fee or the Platform Fee will be effective for the Account starting in the next month that begins at least 30 days after Gainy sends or posts such notice.'
      ]
    },
    {
      title: '6. Valuation',
      content: 'The assets in the Account shall be valued solely by DriveWealth.'
    },
    {
      title: '7. Responsibility for Expenses',
      content: 'Gainy charges Client the Advisory Fee and/or Platform Fee as provided in Section 5. Clients may be subject to additional fees, such as fees embedded in the products, including without limitation ETFs or mutual funds, held in the Account. The fees and expenses set forth herein do not include additional fees or expenses for optional brokerage services or products that Drivewealth may charge Clients. '
    },
    {
      title: '8. Payment of Fees',
      content: 'Gainy may, in its discretion, either (a) cause the Account to pay to Gainy any amount owing to Gainy or DriveWealth under this Agreement or (b) bill Client for such amount, in which case Client shall pay such amount to Gainy within ten (10) days of Client’s receipt of such bill. If Gainy causes the Account to pay Gainy or DriveWealth directly, Gainy will inform DriveWealth of the amount of the Advisory Fee or Platform Fee to be paid to Gainy directly from the Account and notify Client, after the Advisory Fee and/or Platform Fee has been charged, the amount of the Advisory Fee or Platform Fee and the net market values of Client’s assets on which the Advisory Fee and/or Platform Fee has been based. Notification to Client will be through Client’s user account on the Site, the App, or by email at the address(es) provided by Client to Gainy.',
      subcontent: 'The Client may opt to pay for Gainy services under this Agreement by credit card. In the event Client prefers to pay Gainy via credit card, Client shall provide a credit card for Gainy to keep on file, and authorizes Gainy to charge the designated card for the amount owing to Gainy on a monthly basis.  If for any reason, the designated card cannot be charged for the full amount of the fees owed to Gainy, Gainy may, in its discretion, use the Account to charge the balance owed to Gainy as set forth in the first paragraph of this Section and in Section 5 of this Agreement.',
    },
    {
      title: '9. Portfolio Transactions',
      content: 'Gainy will place orders for the execution of transactions for the Client Account in accordance with Gainy’s Form ADV Part 2 (available at <a href="https://www.gainy.app/adv" target="_blank">https://www.gainy.app/adv</a>) as may be amended from time to time. Gainy shall not have any responsibility for obtaining for the Account the best prices or any particular commission rates.'
    },
    {
      title: '10. Client-Defined Portfolios',
      content: 'Client authorizes Gainy to effect Securities transactions in Client’s Account in accordance with the Security selection and allocation elected by Client. However, Client understands and agrees that Gainy retains full discretion over Client-Defined Portfolios. In certain situations, Securities and allocations in the Client- Defined Portfolio may differ from Securities and allocations elected by Client. A lack of liquidity, market conditions, unavailable pricing, software failure, tax considerations, wash sale prevention, and other factors may prevent Gainy from effecting transactions in accordance with Client’s specified elections.'
    },
    {
      title: '11. Limitation of Liability and Indemnification',
      content: '(a) To the extent permitted under applicable law, Client understands and agrees that Gainy will not be liable to Client for any losses, expenses, damages, liabilities, charges and claims of any kind or nature whatsoever (including without limitation any legal expenses and costs and expenses relating to investigating or defending any demands, charges and claims) (collectively, “Losses”) incurred by Client with respect to any Accounts, except to the extent that such Losses are actual losses of the Client proven with reasonable certainty and are the direct result of an act or omission taken or omitted by Gainy during the term of this Agreement which constitutes willful misfeasance, bad faith or gross negligence under this Agreement. Without limitation, Gainy shall not be liable for Losses resulting from or in any way arising out of (i) any action of the Client or its previous advisers or other agents, (ii) force majeure or other events beyond the control of Gainy, including without limitation any failure, default or delay in performance resulting from computer or other electronic or mechanical equipment failure, unauthorized access, strikes, failure of common carrier or utility systems, severe weather or breakdown in communications not reasonably within the control of Gainy or other causes commonly known as “acts of god”, or (iii) general market conditions unrelated to any violation of this Agreement by Gainy.',
      subcontent: '(b) Client (and in addition, for entity accounts, Client Representative) shall reimburse, indemnify, defend and hold harmless Gainy, its affiliates and their directors, officers, shareholders, employees and any person controlled by or controlling Gainy from and against any and all Losses relating to this Agreement or the Account arising out of any misrepresentations or act or omissions or alleged act or omission on the part of the Client (or Client Representatives) or previous advisers or the custodian or any of their agents, except if such Losses are the direct result of Gainy’s willful misfeasance, bad faith or gross negligence in the performance of Gainy’s duties or by reason of Gainy’s reckless disregard of its obligations and duties hereunder. In addition to the above indemnities, for entity Clients, the Client Representative shall further indemnify and defend Gainy and Gainy’s directors, officers, shareholders, employees and affiliates (“<b>Indemnified Persons</b>”) and hold them harmless from and against any and all claims, losses, damages, liabilities and expenses, as they are incurred, resulting from or in connection to Client’s assertion of Client Representative’s lack of proper authorization from Client to enter into this Agreement. Notwithstanding anything in this Section 11 or otherwise in this Agreement to the contrary, nothing herein shall constitute a waiver or limitation of any rights that Client may have under any federal or state securities laws, which rights may arise even if Gainy’s recommendation or other act or failure to act hereunder does not constitute willful misfeasance, bad faith or gross negligence in the performance of Gainy’s duties or by reason of Gainy’s reckless disregard of its obligations and duties hereunder.'
    },
    {
      title: '12. Proxies',
      content: 'Client acknowledges and agrees that Gainy will not engage in proxy voting for the Securities held in the Account. Any proxy voting required to be made for the Securities shall be handled directly by the Client in accordance with the proxy voting standards of each Security.'
    },
    {
      title: '13. Termination; Withdrawals',
      content: 'This Agreement may be terminated by either party with or without cause by notice to the other party. Any notice given hereunder shall be provided by Client to Gainy through the Site and by Gainy to Client through the primary email address in Client’s Account Application as Client shall update from time to time. Client may withdraw all or part of the Account by notifying Gainy at any time provided that all partial withdrawals comply with Gainy’s required Account minimums as posted on the Site and updated from time to time, unless Gainy otherwise consents in advance. Client’s withdrawal of all of the Account under this Agreement, or Client’s withdrawal that results in an Account balance below the minimum as provided in Section 2 hereof will terminate this Agreement. Upon termination of this Agreement, Sections 8 (only as to fees accruing prior to termination), 11, 13, 16, and 17 through 23 shall survive such termination. Client understands and agrees that upon termination of this Agreement Gainy may determine to liquidate immediately all holdings in the Plan and the Account, and subject to Section 11 hereof, Gainy shall not be liable to Client to any consequences of such liquidation.'
    },
    {
      title: '14. Account Statements',
      content: 'Client shall receive quarterly account statements via electronic delivery from the Custodian. Gainy may, but is not required to, from time to time, provide additional information about the Account.'
    },
    {
      title: '15. Independent Contractor',
      content: 'Gainy is and will hereafter act as an independent contractor and not as an employee of Client, and nothing in this Agreement may be interpreted or construed to create any employment, partnership, joint venture or other relationship between Gainy and Client.'
    },
    {
      title: '16. Delivery of Information',
      subcontent: 'Gainy will annually deliver, electronically and without charge, Gainy’s brochure required by the Advisers Act.',
      content: 'Client acknowledges electronic delivery of Gainy’s brochure that would be required to be delivered under the Investment Advisers Act of 1940 (the “Advisers Act”) (including the information in Part 2 of Gainy’s Form ADV), which is available on the Site and the App and provided here by link: <a href="https://www.gainy.app/adv" target="_blank">https://www.gainy.app/adv</a>'
    },
    {
      title: '17. Governing Law',
      content: 'This Agreement shall be governed exclusively by and construed and interpreted in accordance with the U.S. Federal Arbitration Act, federal arbitration law, and the laws of the State of California, excluding its provisions on conflicts or choice of laws. Except as otherwise expressly set forth in Section 18 of this Agreement below, any legal action or proceeding arising under this Agreement shall be brought and resolved solely and exclusively in the State Court located in California.'
    },
    {
      title: '18. Arbitration',
      content: 'Any dispute, claim or controversy arising out of or relating to the advisory services provided by Gainy, this Agreement or the breach, termination, enforcement, interpretation, or validity thereof, including the determination of the scope or applicability of this Agreement to arbitrate (each a “<b>Dispute</b>”), shall be resolved solely by binding, individual arbitration rather than a class, representative or consolidated action or proceeding. Client and Gainy each further agree that the U.S. Federal Arbitration Act governs the interpretation and enforcement of this Agreement, and that each party is waiving the right to a trial by jury or to participate in a class action. This arbitration provision shall survive termination of this Agreement.',
      lists: [
        'Exceptions. As limited exceptions to mandatory arbitration as set forth in this Section, the parties each retain the right to seek injunctive or other equitable relief from a court to prevent (or enjoin) the infringement or misappropriation of our intellectual property rights.',
        'Conducting Arbitration and Arbitration Rules. The arbitration will be conducted by the American Arbitration Association (“AAA”) under its Consumer Arbitration Rules (the “AAA Rules”) then in effect, except as modified by this Agreement. The AAA Rules are available at www.adr.org or by calling 1-800-778-7879. A party who wishes to start arbitration must submit a written Demand for Arbitration to AAA and give notice to the other party as specified in the AAA Rules. The AAA provides a form Demand for Arbitration at www.adr.org.',
        'If Client’s claim is for U.S. $10,000 or less, Client may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, through a telephonic or video-conference hearing, or by an in- person hearing as established by the AAA Rules. If Client’s claim exceeds U.S. $10,000, the right to a hearing will be determined by the AAA Rules. Any arbitration hearings will take place in San Mateo County, California, unless the parties both agree in writing to a different location. Client and Gainy agree that the arbitrator shall have exclusive authority to decide all issues relating to the interpretation, applicability, enforceability, and scope of the terms of this Agreement.',
        'Arbitration Costs. Payment of all filing, administration and arbitrator fees will be governed by the AAA Rules. If Client prevails in arbitration Client will be entitled to an award of attorneys’ fees and expenses to the extent provided under applicable law.',
        ' Effect of Changes on Arbitration. Gainy reserves the right to modify this Section 18 at any time upon 30 days’ written notice to you. Any such modification shall be prospective and shall not affect previously filed claims. By keeping your client account with Gainy or by continuing to use services provided by Gainy, you agree to and accept all terms and conditions of any modifications.',
        'Class Action Waiver. Client AND GAINY AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, if our Dispute is resolved through arbitration, the arbitrator may not consolidate another person\'s claims with Client’s claims and may not otherwise preside over any form of a representative or class proceeding. If any of the specific provisions within this Section are found to be unenforceable, the remainder of this Section shall not be affected thereby and, to this extent, the provisions of this Section shall be deemed to be severable. If there is a final judicial determination that any particular claim (or a request for particular relief) cannot be arbitrated in accordance with this Section, then only that claim (or only that request for relief) may be brought in court. All other claims (or requests for relief) remain subject to this Section.'
      ]
    },
    {
      title: '19. Notices',
      content: 'All notices and communications under this Agreement must be made through the Site or by email. Gainy’s contact information for this purpose is support@gainy.app, and Client’s contact information for this purpose is contained in Client’s user account on the Site and the primary email address(es) in Client’s Account Application as Client shall update from time to time.'
    },
    {
      title: '20. Severability and Amendment',
      content: 'The invalidity or unenforceability of any provision hereof shall in no way affect the validity or enforceability of any and all other provisions hereof. Client acknowledges and agrees that Gainy may amend this Agreement from time to time, and Client’s failure to object to any such amendments within thirty (30) days of written notice to Client shall be deemed acceptance by Client of the amended Agreement.'
    },
    {
      title: '21. Waiver or Modification',
      content: 'Gainy’s waiver or modification of any condition or obligation hereunder shall not be construed as a waiver or modification of any other condition or obligation, nor shall Gainy’s waiver or modification granted on one occasion be construed as applying to any other occasion.'
    },
    {
      title: '22. Entire Agreement',
      content: 'This Agreement, together with the Customer Brokerage and Custody Agreement, is the entire agreement of the parties regarding the subject matter hereof and supersedes all prior or contemporaneous written or oral negotiations, correspondence, agreements, and understandings (including without limitation any and all preexisting client account agreements, which are hereby cancelled). However, the parties may choose to enter into separate agreements between them regarding different subject matters or investment programs.'
    },
    {
      title: '23. No Third-Party Beneficiaries',
      content: 'Neither party intends for this Agreement to benefit any third party not expressly named in this Agreement.'
    },
    {
      title: '24. Death, Disability, or Divorce',
      content: 'If a Client is an individual, the Client’s death, disability or incompetency will not automatically terminate or change the terms of this Agreement. However, the Client’s executor, guardian or attorney-in-fact may terminate this Agreement by giving written notice to Gainy. In the event that Client is a joint Account, both Account holders agree that if the Account ever becomes the subject of a dispute between Account holders, and Gainy becomes aware of the dispute, Gainy may refuse to disburse or allow for the termination of this Agreement without the consent of both joint Account holders. Further, both Account holders agree that in the event that one Account holder provides instructions to Gainy, even if the instructions are to terminate the Agreement and disburse all funds from the Account to one of the Account holders, Gainy may do so without the permission of the other Account holder and will have no liability to either Account holder.'
    }
  ]
};
