export const config = {
  title: 'You (“Client”) and Gainy, Inc., a Delaware limited liability company and a Securities Exchange Commission (the “SEC”) registered investment adviser (“Gainy”), agree to enter into an investment advisory relationship (the “Agreement”) pursuant to which Gainy shall exclusively manage the assets in account(s) that you establish at DriveWealth LLC (“DriveWealth”). This Agreement is solely available to residents of the United States and its territories. This Agreement is effective as of the first day a brokerage account is opened in connection with this Agreement and is ready to receive trading instructions from Gainy (the “Effective Date”). In consideration of the mutual covenants herein, Client and Gainy agree as follows:',
  buttonText: 'I accept',
  list: [
    {
      title: 'Services',
      content: 'Client appoints Gainy to exclusively manage one or more accounts established and owned by Client at DriveWealth (each the “<b>Client Account</b> ,” “ <b>DriveWealth Account</b> ” or “ <b>Account</b>”). Gainy shall manage the Accounts in accordance with (i) an investment plan recommended by Gainy to Client from time to time based on profile information provided by Client (“<b>Investment Profile</b> ”), and in accordance with certain additional investment options designated by Client (the “<b>Plan</b>” ), or (ii) an Investment Profile customized by Client (“<b>Client-Defined Portfolios</b>”).  Gainy shall manage such Client- Defined Portfolios in accordance with the investment allocation elected by Client, although Gainy retains full investment discretion over such Client-Defined Portfolios and its allocation. Client authorizes Gainy, on Client’s behalf and at Client’s risk, to supervise and direct the investment and reinvestment of assets in the Client Accounts, with full authority and discretion, without consultation with Client, to purchase and sell securities, including but not limited to stocks, exchange traded funds (“<b>ETFs</b>”), mutual funds (including without limitation money market mutual funds as separate investments from the Plan), and/or similarly traded instruments (collectively, the “<b>Securities</b>>”), as well as to manage cash balances within the Client Accounts. Gainy shall have the sole authority to issue trading instructions to purchase and sell Securities in the Client Accounts based on the discretionary authority granted to Gainy by Client under this Agreement. Gainy shall not have any duty or obligation to advise or take any action on behalf of Client in any legal proceedings, including bankruptcies or class actions, involving Securities held in, or formerly held in, the Account, or involving the issuers of such Securities.',
      subcontent: 'Notwithstanding anything in this Agreement to the contrary, Gainy shall have no authority hereunder to take or have possession of any assets in the Accounts or to direct delivery of any Securities or payment of any funds held in the Account to itself or to direct any disposition of such Securities or funds, except to Client, as directed by Client and to a Client controlled account, pursuant to valid legal authority, as provided in Section 8 hereof.'
    },
    {
      title: 'Representations and Warranties.',
      content: 'Client represents and warrants to Gainy as follows:',
      lists: [
        'Client has the requisite legal capacity, authority, and power to execute, deliver and perform his or her obligations under this Agreement. This Agreement has been duly authorized, executed and delivered by Client and is the legal, valid, and binding agreement of Client, enforceable against Client in accordance with its terms. Client’s execution of this Agreement and the performance of his or her obligations hereunder do not conflict with or violate any obligations by which Client is bound, whether arising by contract, operation of law or otherwise. If the Client is an entity, the individual trustee, agent, representative or nominee (the “<b>Client Representative</b>”) executing this Agreement on behalf of Client has the requisite legal capacity, authority, and power to execute, deliver and perform such execution and the obligations under this Agreement as applicable. The services described herein are authorized under the Client’s applicable articles, certificate, charter, operating agreement, partnership agreement, plan document, trust or organizational, delegation or formation documents or law. Upon Gainy’s  request, Client will deliver to Gainy evidence of Client’s and Client Representative’s authority. Client will promptly notify Gainy of any change in such authority.'
      ]
    }
  ]
};
