name: "Main"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style-check:
    name: "Style Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: sudo apt install nodejs npm

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Lint:CSS
        run: npm run lint:css

      - name: Lint:ES
        run: npm run lint:es

  terraform:
    name: "Terraform"
    uses: ./.github/workflows/terraform.yml
    with:
      env: production
      only_plan: ${{ !(github.ref == 'refs/heads/main' && github.event_name == 'push') }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
